name: Tag a new version ðŸ·ï¸

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-build-number:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      # - name: Get the version
      #   id: code-version
      #   run: echo "API_VERSION=$(sh ./_scripts/get_version_local.sh)" >> $GITHUB_ENV

      # - name: Create a new tag
      #   id: create-tag
      #   run: |
      #     echo "The new tag will be: ${{ env.API_VERSION }}"
      #     git tag ${{ env.API_VERSION }}
      #     git push origin ${{ env.API_VERSION }}
